apiVersion: v1
kind: ConfigMap
metadata:
  name: practica-db-initdb-config
  labels:
    workspace: scalian_training
data:
  initdb.sql: |
    use knights;

    CREATE TABLE favorite_colors (
      name VARCHAR(20),
      color VARCHAR(10)
    );

    INSERT INTO favorite_colors
      (name, color)
    VALUES
      ('Lancelot', 'blue'),
      ('Galahad', 'yellow');