apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: practica-db-pv-claim
  labels:
    workspace: scalian_training
    app: practica
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi